# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAIN.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 190, 641, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.imageLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.imageLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.imageLayout.setContentsMargins(0, 0, 0, 0)
        self.imageLayout.setObjectName("imageLayout")
        self.btnPnP = QtWidgets.QPushButton(self.centralwidget)
        self.btnPnP.setGeometry(QtCore.QRect(20, 230, 111, 23))
        self.btnPnP.setAutoDefault(False)
        self.btnPnP.setObjectName("btnPnP")
        self.chkDetectLoop = QtWidgets.QCheckBox(self.centralwidget)
        self.chkDetectLoop.setEnabled(True)
        self.chkDetectLoop.setGeometry(QtCore.QRect(110, 370, 121, 17))
        self.chkDetectLoop.setChecked(False)
        self.chkDetectLoop.setObjectName("chkDetectLoop")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 78, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSource = QtWidgets.QLabel(self.layoutWidget)
        self.labelSource.setObjectName("labelSource")
        self.verticalLayout_2.addWidget(self.labelSource)
        self.rbSourceStill = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbSourceStill.setChecked(True)
        self.rbSourceStill.setObjectName("rbSourceStill")
        self.verticalLayout_2.addWidget(self.rbSourceStill)
        self.rbSourceAgent = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbSourceAgent.setObjectName("rbSourceAgent")
        self.verticalLayout_2.addWidget(self.rbSourceAgent)
        self.rbSourceUeye = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbSourceUeye.setObjectName("rbSourceUeye")
        self.verticalLayout_2.addWidget(self.rbSourceUeye)
        self.rbSourceUsb = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbSourceUsb.setObjectName("rbSourceUsb")
        self.verticalLayout_2.addWidget(self.rbSourceUsb)
        self.rbSourceVideo = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbSourceVideo.setObjectName("rbSourceVideo")
        self.verticalLayout_2.addWidget(self.rbSourceVideo)
        self.btnDetect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetect.setGeometry(QtCore.QRect(10, 370, 91, 23))
        self.btnDetect.setAutoDefault(False)
        self.btnDetect.setObjectName("btnDetect")
        self.lbElisaAgents = QtWidgets.QLabel(self.centralwidget)
        self.lbElisaAgents.setGeometry(QtCore.QRect(10, 700, 1191, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.lbElisaAgents.setFont(font)
        self.lbElisaAgents.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbElisaAgents.setObjectName("lbElisaAgents")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 47, 13))
        self.label_3.setObjectName("label_3")
        self.slideDetect = QtWidgets.QSlider(self.centralwidget)
        self.slideDetect.setGeometry(QtCore.QRect(10, 400, 161, 22))
        self.slideDetect.setOrientation(QtCore.Qt.Horizontal)
        self.slideDetect.setObjectName("slideDetect")
        self.lbDetectRate = QtWidgets.QLabel(self.centralwidget)
        self.lbDetectRate.setGeometry(QtCore.QRect(10, 420, 201, 28))
        self.lbDetectRate.setObjectName("lbDetectRate")
        self.lbDetectCount = QtWidgets.QLabel(self.centralwidget)
        self.lbDetectCount.setGeometry(QtCore.QRect(10, 450, 201, 91))
        self.lbDetectCount.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbDetectCount.setObjectName("lbDetectCount")
        self.chkPnP = QtWidgets.QCheckBox(self.centralwidget)
        self.chkPnP.setEnabled(True)
        self.chkPnP.setGeometry(QtCore.QRect(140, 230, 121, 17))
        self.chkPnP.setCheckable(True)
        self.chkPnP.setChecked(False)
        self.chkPnP.setObjectName("chkPnP")
        self.btnSelectVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectVideo.setGeometry(QtCore.QRect(250, 140, 25, 25))
        self.btnSelectVideo.setObjectName("btnSelectVideo")
        self.txtVideoFile = QtWidgets.QTextEdit(self.centralwidget)
        self.txtVideoFile.setGeometry(QtCore.QRect(20, 140, 221, 23))
        self.txtVideoFile.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtVideoFile.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtVideoFile.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtVideoFile.setObjectName("txtVideoFile")
        self.lbLog = QtWidgets.QLabel(self.centralwidget)
        self.lbLog.setGeometry(QtCore.QRect(10, 770, 1081, 51))
        self.lbLog.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbLog.setObjectName("lbLog")
        self.lbMouseAngle = QtWidgets.QLabel(self.centralwidget)
        self.lbMouseAngle.setGeometry(QtCore.QRect(330, 50, 47, 13))
        self.lbMouseAngle.setText("")
        self.lbMouseAngle.setObjectName("lbMouseAngle")
        self.chkDebug = QtWidgets.QCheckBox(self.centralwidget)
        self.chkDebug.setGeometry(QtCore.QRect(20, 680, 181, 17))
        self.chkDebug.setChecked(False)
        self.chkDebug.setObjectName("chkDebug")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(890, 100, 371, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 191, 16))
        self.label_6.setObjectName("label_6")
        self.lbPosAxs = QtWidgets.QLabel(self.tab)
        self.lbPosAxs.setGeometry(QtCore.QRect(0, 30, 231, 71))
        self.lbPosAxs.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbPosAxs.setObjectName("lbPosAxs")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(0, 150, 47, 13))
        self.label_5.setObjectName("label_5")
        self.lbRvec = QtWidgets.QLabel(self.tab)
        self.lbRvec.setGeometry(QtCore.QRect(0, 160, 231, 51))
        self.lbRvec.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbRvec.setObjectName("lbRvec")
        self.lbAgents = QtWidgets.QLabel(self.tab)
        self.lbAgents.setGeometry(QtCore.QRect(0, 220, 201, 301))
        self.lbAgents.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbAgents.setObjectName("lbAgents")
        self.lbTvec = QtWidgets.QLabel(self.tab)
        self.lbTvec.setGeometry(QtCore.QRect(0, 110, 231, 41))
        self.lbTvec.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbTvec.setObjectName("lbTvec")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(0, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 350, 181, 16))
        self.label_2.setObjectName("label_2")
        self.lbCalMarkersId = QtWidgets.QLabel(self.tab)
        self.lbCalMarkersId.setGeometry(QtCore.QRect(0, 440, 47, 61))
        self.lbCalMarkersId.setObjectName("lbCalMarkersId")
        self.lbCalMarkersPos = QtWidgets.QLabel(self.tab)
        self.lbCalMarkersPos.setGeometry(QtCore.QRect(30, 440, 141, 61))
        self.lbCalMarkersPos.setObjectName("lbCalMarkersPos")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 97, 130))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOverlay = QtWidgets.QLabel(self.layoutWidget1)
        self.labelOverlay.setObjectName("labelOverlay")
        self.verticalLayout.addWidget(self.labelOverlay)
        self.rbOverlayMouse = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbOverlayMouse.setObjectName("rbOverlayMouse")
        self.verticalLayout.addWidget(self.rbOverlayMouse)
        self.rbOverlayRotational = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbOverlayRotational.setObjectName("rbOverlayRotational")
        self.verticalLayout.addWidget(self.rbOverlayRotational)
        self.rbOverlayCenter = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbOverlayCenter.setObjectName("rbOverlayCenter")
        self.verticalLayout.addWidget(self.rbOverlayCenter)
        self.rbOverlayNone = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbOverlayNone.setObjectName("rbOverlayNone")
        self.verticalLayout.addWidget(self.rbOverlayNone)
        self.rvOverlayCoverage = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rvOverlayCoverage.setObjectName("rvOverlayCoverage")
        self.verticalLayout.addWidget(self.rvOverlayCoverage)
        self.chkReprojectionTest = QtWidgets.QCheckBox(self.tab_5)
        self.chkReprojectionTest.setGeometry(QtCore.QRect(30, 260, 181, 17))
        self.chkReprojectionTest.setChecked(False)
        self.chkReprojectionTest.setObjectName("chkReprojectionTest")
        self.chkCalstick = QtWidgets.QCheckBox(self.tab_5)
        self.chkCalstick.setGeometry(QtCore.QRect(30, 280, 181, 17))
        self.chkCalstick.setChecked(True)
        self.chkCalstick.setObjectName("chkCalstick")
        self.chkGrid = QtWidgets.QCheckBox(self.tab_5)
        self.chkGrid.setGeometry(QtCore.QRect(30, 390, 131, 17))
        self.chkGrid.setChecked(True)
        self.chkGrid.setObjectName("chkGrid")
        self.chkCalMarkers = QtWidgets.QCheckBox(self.tab_5)
        self.chkCalMarkers.setGeometry(QtCore.QRect(30, 300, 131, 17))
        self.chkCalMarkers.setChecked(True)
        self.chkCalMarkers.setObjectName("chkCalMarkers")
        self.chkXvision = QtWidgets.QCheckBox(self.tab_5)
        self.chkXvision.setGeometry(QtCore.QRect(30, 320, 131, 17))
        self.chkXvision.setChecked(True)
        self.chkXvision.setObjectName("chkXvision")
        self.btnFrameRate = QtWidgets.QPushButton(self.tab_5)
        self.btnFrameRate.setGeometry(QtCore.QRect(30, 430, 87, 23))
        self.btnFrameRate.setObjectName("btnFrameRate")
        self.slideScreen = QtWidgets.QSlider(self.tab_5)
        self.slideScreen.setGeometry(QtCore.QRect(120, 430, 160, 22))
        self.slideScreen.setSliderPosition(6)
        self.slideScreen.setOrientation(QtCore.Qt.Horizontal)
        self.slideScreen.setObjectName("slideScreen")
        self.lbFrameRate = QtWidgets.QLabel(self.tab_5)
        self.lbFrameRate.setGeometry(QtCore.QRect(20, 460, 271, 28))
        self.lbFrameRate.setObjectName("lbFrameRate")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 40, 160, 88))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rbDestUndistorted = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbDestUndistorted.setObjectName("rbDestUndistorted")
        self.verticalLayout_5.addWidget(self.rbDestUndistorted)
        self.rbDestRaw = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbDestRaw.setObjectName("rbDestRaw")
        self.verticalLayout_5.addWidget(self.rbDestRaw)
        self.rbDestRectified = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbDestRectified.setObjectName("rbDestRectified")
        self.verticalLayout_5.addWidget(self.rbDestRectified)
        self.rbDestNone = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbDestNone.setObjectName("rbDestNone")
        self.verticalLayout_5.addWidget(self.rbDestNone)
        self.labelDestination = QtWidgets.QLabel(self.tab_5)
        self.labelDestination.setGeometry(QtCore.QRect(130, 20, 111, 16))
        self.labelDestination.setObjectName("labelDestination")
        self.btnScreenShot = QtWidgets.QPushButton(self.tab_5)
        self.btnScreenShot.setGeometry(QtCore.QRect(140, 140, 75, 23))
        self.btnScreenShot.setObjectName("btnScreenShot")
        self.lbViz = QtWidgets.QLabel(self.tab_5)
        self.lbViz.setGeometry(QtCore.QRect(10, 560, 301, 16))
        self.lbViz.setObjectName("lbViz")
        self.btnFolder = QtWidgets.QPushButton(self.tab_5)
        self.btnFolder.setGeometry(QtCore.QRect(230, 140, 61, 23))
        self.btnFolder.setAutoDefault(False)
        self.btnFolder.setObjectName("btnFolder")
        self.chkXhat = QtWidgets.QCheckBox(self.tab_5)
        self.chkXhat.setGeometry(QtCore.QRect(30, 340, 131, 17))
        self.chkXhat.setObjectName("chkXhat")
        self.chkMarkerIds = QtWidgets.QCheckBox(self.tab_5)
        self.chkMarkerIds.setGeometry(QtCore.QRect(30, 360, 131, 17))
        self.chkMarkerIds.setObjectName("chkMarkerIds")
        self.chkXodometry = QtWidgets.QCheckBox(self.tab_5)
        self.chkXodometry.setGeometry(QtCore.QRect(200, 260, 131, 17))
        self.chkXodometry.setObjectName("chkXodometry")
        self.chkXpredict = QtWidgets.QCheckBox(self.tab_5)
        self.chkXpredict.setGeometry(QtCore.QRect(200, 280, 131, 17))
        self.chkXpredict.setObjectName("chkXpredict")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.chkGamePad = QtWidgets.QCheckBox(self.tab_6)
        self.chkGamePad.setGeometry(QtCore.QRect(20, 220, 87, 17))
        self.chkGamePad.setChecked(False)
        self.chkGamePad.setObjectName("chkGamePad")
        self.lbControlTextBox = QtWidgets.QLabel(self.tab_6)
        self.lbControlTextBox.setGeometry(QtCore.QRect(20, 250, 261, 321))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.lbControlTextBox.setFont(font)
        self.lbControlTextBox.setAutoFillBackground(False)
        self.lbControlTextBox.setFrameShape(QtWidgets.QFrame.Box)
        self.lbControlTextBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbControlTextBox.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbControlTextBox.setObjectName("lbControlTextBox")
        self.slideBeta = QtWidgets.QSlider(self.tab_6)
        self.slideBeta.setGeometry(QtCore.QRect(210, 210, 61, 22))
        self.slideBeta.setMinimum(5)
        self.slideBeta.setMaximum(50)
        self.slideBeta.setSingleStep(1)
        self.slideBeta.setProperty("value", 5)
        self.slideBeta.setSliderPosition(5)
        self.slideBeta.setOrientation(QtCore.Qt.Horizontal)
        self.slideBeta.setObjectName("slideBeta")
        self.lbBeta = QtWidgets.QLabel(self.tab_6)
        self.lbBeta.setGeometry(QtCore.QRect(290, 220, 47, 13))
        self.lbBeta.setObjectName("lbBeta")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setGeometry(QtCore.QRect(240, 150, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(240, 120, 47, 13))
        self.label_8.setObjectName("label_8")
        self.slideV = QtWidgets.QSlider(self.tab_6)
        self.slideV.setGeometry(QtCore.QRect(170, 120, 51, 22))
        self.slideV.setMinimum(-50)
        self.slideV.setMaximum(50)
        self.slideV.setSliderPosition(0)
        self.slideV.setOrientation(QtCore.Qt.Horizontal)
        self.slideV.setObjectName("slideV")
        self.slideOmega = QtWidgets.QSlider(self.tab_6)
        self.slideOmega.setGeometry(QtCore.QRect(170, 150, 61, 22))
        self.slideOmega.setMinimum(-50)
        self.slideOmega.setMaximum(50)
        self.slideOmega.setProperty("value", 0)
        self.slideOmega.setSliderPosition(0)
        self.slideOmega.setOrientation(QtCore.Qt.Horizontal)
        self.slideOmega.setObjectName("slideOmega")
        self.btnVflip = QtWidgets.QPushButton(self.tab_6)
        self.btnVflip.setGeometry(QtCore.QRect(130, 120, 31, 23))
        self.btnVflip.setAutoDefault(False)
        self.btnVflip.setObjectName("btnVflip")
        self.btnOflip = QtWidgets.QPushButton(self.tab_6)
        self.btnOflip.setGeometry(QtCore.QRect(130, 150, 31, 23))
        self.btnOflip.setAutoDefault(False)
        self.btnOflip.setObjectName("btnOflip")
        self.btnElisaCalibrate = QtWidgets.QPushButton(self.tab_6)
        self.btnElisaCalibrate.setGeometry(QtCore.QRect(20, 30, 121, 23))
        self.btnElisaCalibrate.setAutoDefault(False)
        self.btnElisaCalibrate.setObjectName("btnElisaCalibrate")
        self.slideElisa = QtWidgets.QSlider(self.tab_6)
        self.slideElisa.setGeometry(QtCore.QRect(150, 30, 71, 22))
        self.slideElisa.setProperty("value", 20)
        self.slideElisa.setOrientation(QtCore.Qt.Horizontal)
        self.slideElisa.setObjectName("slideElisa")
        self.lbElisa = QtWidgets.QLabel(self.tab_6)
        self.lbElisa.setGeometry(QtCore.QRect(30, 60, 389, 20))
        self.lbElisa.setObjectName("lbElisa")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.slidePixClock = QtWidgets.QSlider(self.tab_4)
        self.slidePixClock.setGeometry(QtCore.QRect(110, 70, 91, 22))
        self.slidePixClock.setMinimum(10)
        self.slidePixClock.setMaximum(71)
        self.slidePixClock.setProperty("value", 71)
        self.slidePixClock.setOrientation(QtCore.Qt.Horizontal)
        self.slidePixClock.setObjectName("slidePixClock")
        self.slideExposure = QtWidgets.QSlider(self.tab_4)
        self.slideExposure.setGeometry(QtCore.QRect(110, 100, 91, 22))
        self.slideExposure.setProperty("value", 5)
        self.slideExposure.setOrientation(QtCore.Qt.Horizontal)
        self.slideExposure.setObjectName("slideExposure")
        self.slideFPS = QtWidgets.QSlider(self.tab_4)
        self.slideFPS.setGeometry(QtCore.QRect(110, 140, 91, 22))
        self.slideFPS.setProperty("value", 50)
        self.slideFPS.setOrientation(QtCore.Qt.Horizontal)
        self.slideFPS.setObjectName("slideFPS")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_14.setObjectName("label_14")
        self.lbPixelClock = QtWidgets.QLabel(self.tab_4)
        self.lbPixelClock.setGeometry(QtCore.QRect(210, 70, 61, 16))
        self.lbPixelClock.setObjectName("lbPixelClock")
        self.lbExposure = QtWidgets.QLabel(self.tab_4)
        self.lbExposure.setGeometry(QtCore.QRect(220, 100, 61, 16))
        self.lbExposure.setObjectName("lbExposure")
        self.lbFPS = QtWidgets.QLabel(self.tab_4)
        self.lbFPS.setGeometry(QtCore.QRect(220, 140, 61, 16))
        self.lbFPS.setObjectName("lbFPS")
        self.chkExposeAuto = QtWidgets.QCheckBox(self.tab_4)
        self.chkExposeAuto.setGeometry(QtCore.QRect(280, 110, 51, 17))
        self.chkExposeAuto.setChecked(False)
        self.chkExposeAuto.setObjectName("chkExposeAuto")
        self.chkFPSmax = QtWidgets.QCheckBox(self.tab_4)
        self.chkFPSmax.setGeometry(QtCore.QRect(280, 130, 51, 17))
        self.chkFPSmax.setChecked(False)
        self.chkFPSmax.setObjectName("chkFPSmax")
        self.lbCursorPos = QtWidgets.QLabel(self.tab_4)
        self.lbCursorPos.setGeometry(QtCore.QRect(0, 210, 721, 21))
        self.lbCursorPos.setObjectName("lbCursorPos")
        self.btnCamParLoad = QtWidgets.QPushButton(self.tab_4)
        self.btnCamParLoad.setGeometry(QtCore.QRect(10, 20, 161, 23))
        self.btnCamParLoad.setAutoDefault(False)
        self.btnCamParLoad.setObjectName("btnCamParLoad")
        self.slideMouseAngle = QtWidgets.QSlider(self.tab_4)
        self.slideMouseAngle.setGeometry(QtCore.QRect(20, 180, 91, 22))
        self.slideMouseAngle.setOrientation(QtCore.Qt.Horizontal)
        self.slideMouseAngle.setObjectName("slideMouseAngle")
        self.tabWidget.addTab(self.tab_4, "")
        self.slideDomainX = QtWidgets.QSlider(self.centralwidget)
        self.slideDomainX.setGeometry(QtCore.QRect(480, 150, 91, 22))
        self.slideDomainX.setMinimum(150)
        self.slideDomainX.setMaximum(1500)
        self.slideDomainX.setSingleStep(50)
        self.slideDomainX.setPageStep(50)
        self.slideDomainX.setProperty("value", 500)
        self.slideDomainX.setOrientation(QtCore.Qt.Horizontal)
        self.slideDomainX.setObjectName("slideDomainX")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(420, 150, 47, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(640, 150, 61, 20))
        self.label_12.setObjectName("label_12")
        self.slideDomainY = QtWidgets.QSlider(self.centralwidget)
        self.slideDomainY.setGeometry(QtCore.QRect(700, 150, 91, 22))
        self.slideDomainY.setMinimum(150)
        self.slideDomainY.setMaximum(1500)
        self.slideDomainY.setSingleStep(50)
        self.slideDomainY.setPageStep(50)
        self.slideDomainY.setProperty("value", 500)
        self.slideDomainY.setOrientation(QtCore.Qt.Horizontal)
        self.slideDomainY.setObjectName("slideDomainY")
        self.lbDomX = QtWidgets.QLabel(self.centralwidget)
        self.lbDomX.setGeometry(QtCore.QRect(570, 150, 47, 16))
        self.lbDomX.setObjectName("lbDomX")
        self.lbDomY = QtWidgets.QLabel(self.centralwidget)
        self.lbDomY.setGeometry(QtCore.QRect(800, 150, 47, 16))
        self.lbDomY.setObjectName("lbDomY")
        self.btnMeas = QtWidgets.QPushButton(self.centralwidget)
        self.btnMeas.setGeometry(QtCore.QRect(10, 330, 121, 23))
        self.btnMeas.setObjectName("btnMeas")
        self.slideElisaGain = QtWidgets.QSlider(self.centralwidget)
        self.slideElisaGain.setGeometry(QtCore.QRect(710, 10, 131, 22))
        self.slideElisaGain.setMinimum(1)
        self.slideElisaGain.setOrientation(QtCore.Qt.Horizontal)
        self.slideElisaGain.setObjectName("slideElisaGain")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(640, 10, 71, 20))
        self.label_7.setObjectName("label_7")
        self.btnVizView = QtWidgets.QPushButton(self.centralwidget)
        self.btnVizView.setGeometry(QtCore.QRect(910, 40, 141, 23))
        self.btnVizView.setObjectName("btnVizView")
        self.chkVizInvert = QtWidgets.QCheckBox(self.centralwidget)
        self.chkVizInvert.setGeometry(QtCore.QRect(980, 10, 70, 17))
        self.chkVizInvert.setObjectName("chkVizInvert")
        self.chkStoreVids = QtWidgets.QCheckBox(self.centralwidget)
        self.chkStoreVids.setGeometry(QtCore.QRect(140, 330, 70, 17))
        self.chkStoreVids.setObjectName("chkStoreVids")
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(120, 10, 170, 130))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.lyObserver = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.lyObserver.setContentsMargins(0, 0, 0, 0)
        self.lyObserver.setObjectName("lyObserver")
        self.lbControl_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.lbControl_2.setObjectName("lbControl_2")
        self.lyObserver.addWidget(self.lbControl_2)
        self.rbObsVis = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.rbObsVis.setChecked(True)
        self.rbObsVis.setObjectName("rbObsVis")
        self.lyObserver.addWidget(self.rbObsVis)
        self.rbObsVisUKF = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.rbObsVisUKF.setChecked(False)
        self.rbObsVisUKF.setObjectName("rbObsVisUKF")
        self.lyObserver.addWidget(self.rbObsVisUKF)
        self.rbObsOdomUKF = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.rbObsOdomUKF.setObjectName("rbObsOdomUKF")
        self.lyObserver.addWidget(self.rbObsOdomUKF)
        self.rbObsFuse = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.rbObsFuse.setObjectName("rbObsFuse")
        self.lyObserver.addWidget(self.rbObsFuse)
        self.rbObsNone = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.rbObsNone.setObjectName("rbObsNone")
        self.lyObserver.addWidget(self.rbObsNone)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(400, 10, 121, 84))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.lyObserver_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.lyObserver_2.setContentsMargins(0, 0, 0, 0)
        self.lyObserver_2.setObjectName("lyObserver_2")
        self.lbControl_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.lbControl_3.setObjectName("lbControl_3")
        self.lyObserver_2.addWidget(self.lbControl_3)
        self.rbInterNone = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rbInterNone.setChecked(True)
        self.rbInterNone.setObjectName("rbInterNone")
        self.lyObserver_2.addWidget(self.rbInterNone)
        self.rbInterDWA = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rbInterDWA.setChecked(False)
        self.rbInterDWA.setObjectName("rbInterDWA")
        self.lyObserver_2.addWidget(self.rbInterDWA)
        self.rbInterPredict = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rbInterPredict.setChecked(False)
        self.rbInterPredict.setObjectName("rbInterPredict")
        self.lyObserver_2.addWidget(self.rbInterPredict)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(300, 5, 97, 181))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbControl = QtWidgets.QLabel(self.layoutWidget_3)
        self.lbControl.setObjectName("lbControl")
        self.verticalLayout_7.addWidget(self.lbControl)
        self.rbControlCenter = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlCenter.setObjectName("rbControlCenter")
        self.verticalLayout_7.addWidget(self.rbControlCenter)
        self.rbControlCustom = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlCustom.setObjectName("rbControlCustom")
        self.verticalLayout_7.addWidget(self.rbControlCustom)
        self.rbControlMouse = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlMouse.setChecked(False)
        self.rbControlMouse.setObjectName("rbControlMouse")
        self.verticalLayout_7.addWidget(self.rbControlMouse)
        self.rbControlRotation = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlRotation.setObjectName("rbControlRotation")
        self.verticalLayout_7.addWidget(self.rbControlRotation)
        self.rbControlCoverage = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlCoverage.setObjectName("rbControlCoverage")
        self.verticalLayout_7.addWidget(self.rbControlCoverage)
        self.rbControlGamePad = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlGamePad.setObjectName("rbControlGamePad")
        self.verticalLayout_7.addWidget(self.rbControlGamePad)
        self.rbControlConstant = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlConstant.setChecked(False)
        self.rbControlConstant.setObjectName("rbControlConstant")
        self.verticalLayout_7.addWidget(self.rbControlConstant)
        self.rbControlNone = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbControlNone.setChecked(True)
        self.rbControlNone.setObjectName("rbControlNone")
        self.verticalLayout_7.addWidget(self.rbControlNone)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(530, 10, 97, 107))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelOverlay_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelOverlay_2.setObjectName("labelOverlay_2")
        self.verticalLayout_6.addWidget(self.labelOverlay_2)
        self.rbOutputElisa3 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbOutputElisa3.setObjectName("rbOutputElisa3")
        self.verticalLayout_6.addWidget(self.rbOutputElisa3)
        self.rbOutputNone = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbOutputNone.setObjectName("rbOutputNone")
        self.verticalLayout_6.addWidget(self.rbOutputNone)
        self.rbOutputSim = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbOutputSim.setObjectName("rbOutputSim")
        self.verticalLayout_6.addWidget(self.rbOutputSim)
        self.rbOutputOpen = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbOutputOpen.setObjectName("rbOutputOpen")
        self.verticalLayout_6.addWidget(self.rbOutputOpen)
        self.btnReloadCfg = QtWidgets.QPushButton(self.centralwidget)
        self.btnReloadCfg.setGeometry(QtCore.QRect(1070, 10, 141, 23))
        self.btnReloadCfg.setObjectName("btnReloadCfg")
        self.btnPathRecalc = QtWidgets.QPushButton(self.centralwidget)
        self.btnPathRecalc.setGeometry(QtCore.QRect(1070, 40, 111, 23))
        self.btnPathRecalc.setObjectName("btnPathRecalc")
        self.chkRetrieveOdometry = QtWidgets.QCheckBox(self.centralwidget)
        self.chkRetrieveOdometry.setGeometry(QtCore.QRect(630, 40, 171, 17))
        self.chkRetrieveOdometry.setChecked(True)
        self.chkRetrieveOdometry.setObjectName("chkRetrieveOdometry")
        self.lbElisaGain = QtWidgets.QLabel(self.centralwidget)
        self.lbElisaGain.setGeometry(QtCore.QRect(850, 10, 47, 13))
        self.lbElisaGain.setObjectName("lbElisaGain")
        self.slideRunOffmm = QtWidgets.QSlider(self.centralwidget)
        self.slideRunOffmm.setGeometry(QtCore.QRect(480, 120, 91, 22))
        self.slideRunOffmm.setMinimum(0)
        self.slideRunOffmm.setMaximum(200)
        self.slideRunOffmm.setSingleStep(10)
        self.slideRunOffmm.setPageStep(10)
        self.slideRunOffmm.setProperty("value", 200)
        self.slideRunOffmm.setOrientation(QtCore.Qt.Horizontal)
        self.slideRunOffmm.setObjectName("slideRunOffmm")
        self.lbControl_4 = QtWidgets.QLabel(self.centralwidget)
        self.lbControl_4.setGeometry(QtCore.QRect(420, 120, 41, 16))
        self.lbControl_4.setObjectName("lbControl_4")
        self.lbRunOff = QtWidgets.QLabel(self.centralwidget)
        self.lbRunOff.setGeometry(QtCore.QRect(580, 120, 47, 16))
        self.lbRunOff.setText("")
        self.lbRunOff.setObjectName("lbRunOff")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1269, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pose Estimation"))
        self.btnPnP.setText(_translate("MainWindow", "PnP Transformation"))
        self.chkDetectLoop.setText(_translate("MainWindow", "Loop"))
        self.labelSource.setText(_translate("MainWindow", "Source"))
        self.rbSourceStill.setText(_translate("MainWindow", "Still"))
        self.rbSourceAgent.setText(_translate("MainWindow", "Still Agents"))
        self.rbSourceUeye.setText(_translate("MainWindow", "Ueye"))
        self.rbSourceUsb.setText(_translate("MainWindow", "UsbCam"))
        self.rbSourceVideo.setText(_translate("MainWindow", "Sample Vid"))
        self.btnDetect.setText(_translate("MainWindow", "Detection"))
        self.lbElisaAgents.setText(_translate("MainWindow", "lbElisaAgents"))
        self.label_3.setText(_translate("MainWindow", "Detected:"))
        self.lbDetectRate.setText(_translate("MainWindow", "Hz"))
        self.lbDetectCount.setText(_translate("MainWindow", "Count:"))
        self.chkPnP.setText(_translate("MainWindow", "Continuous"))
        self.btnSelectVideo.setText(_translate("MainWindow", "..."))
        self.txtVideoFile.setPlaceholderText(_translate("MainWindow", "../img/sample_video.mp4"))
        self.lbLog.setText(_translate("MainWindow", "Errorlog"))
        self.chkDebug.setText(_translate("MainWindow", "Output debug messages"))
        self.label_6.setText(_translate("MainWindow", "Camera Position and Rotation:"))
        self.lbPosAxs.setText(_translate("MainWindow", "Pos"))
        self.label_5.setText(_translate("MainWindow", "Rvec"))
        self.lbRvec.setText(_translate("MainWindow", "Rvec"))
        self.lbAgents.setText(_translate("MainWindow", "Detected:"))
        self.lbTvec.setText(_translate("MainWindow", "Tvec"))
        self.label_4.setText(_translate("MainWindow", "Tvec:"))
        self.label_2.setText(_translate("MainWindow", "Calibration markers id and position:"))
        self.lbCalMarkersId.setText(_translate("MainWindow", "Markers:"))
        self.lbCalMarkersPos.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Camera"))
        self.labelOverlay.setText(_translate("MainWindow", "Overlay"))
        self.rbOverlayMouse.setText(_translate("MainWindow", "Follow Mouse"))
        self.rbOverlayRotational.setText(_translate("MainWindow", "Rotational field"))
        self.rbOverlayCenter.setText(_translate("MainWindow", "Center"))
        self.rbOverlayNone.setText(_translate("MainWindow", "None"))
        self.rvOverlayCoverage.setText(_translate("MainWindow", "Coverage Field"))
        self.chkReprojectionTest.setText(_translate("MainWindow", "Reprojection Test"))
        self.chkCalstick.setText(_translate("MainWindow", "Show Calibration device outline"))
        self.chkGrid.setText(_translate("MainWindow", "Grid"))
        self.chkCalMarkers.setText(_translate("MainWindow", "Calibration Markers"))
        self.chkXvision.setText(_translate("MainWindow", "Xvision (orange)"))
        self.btnFrameRate.setText(_translate("MainWindow", "FrameRate"))
        self.lbFrameRate.setText(_translate("MainWindow", "Hz"))
        self.rbDestUndistorted.setText(_translate("MainWindow", "Undistorted"))
        self.rbDestRaw.setText(_translate("MainWindow", "Raw"))
        self.rbDestRectified.setText(_translate("MainWindow", "Rectified"))
        self.rbDestNone.setText(_translate("MainWindow", "None"))
        self.labelDestination.setText(_translate("MainWindow", "Image Operations"))
        self.btnScreenShot.setText(_translate("MainWindow", "Screenshot"))
        self.lbViz.setText(_translate("MainWindow", "."))
        self.btnFolder.setText(_translate("MainWindow", "->"))
        self.chkXhat.setText(_translate("MainWindow", "Xhat (green)"))
        self.chkMarkerIds.setText(_translate("MainWindow", "Marker ids"))
        self.chkXodometry.setText(_translate("MainWindow", "Xodometry"))
        self.chkXpredict.setText(_translate("MainWindow", "Predict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Visualization"))
        self.chkGamePad.setText(_translate("MainWindow", "Gamepad"))
        self.lbControlTextBox.setText(_translate("MainWindow", "Empty"))
        self.lbBeta.setText(_translate("MainWindow", "Beta"))
        self.label_9.setText(_translate("MainWindow", "Omega"))
        self.label_8.setText(_translate("MainWindow", "Speed"))
        self.btnVflip.setText(_translate("MainWindow", "Flip"))
        self.btnOflip.setText(_translate("MainWindow", "Flip"))
        self.btnElisaCalibrate.setText(_translate("MainWindow", "Calibrate Odometry"))
        self.lbElisa.setText(_translate("MainWindow", "Hz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Control"))
        self.label_10.setText(_translate("MainWindow", "Pixelclock"))
        self.label_13.setText(_translate("MainWindow", "Exposure Time"))
        self.label_14.setText(_translate("MainWindow", "Frame Rate"))
        self.lbPixelClock.setText(_translate("MainWindow", "0"))
        self.lbExposure.setText(_translate("MainWindow", "0"))
        self.lbFPS.setText(_translate("MainWindow", "0"))
        self.chkExposeAuto.setText(_translate("MainWindow", "Auto"))
        self.chkFPSmax.setText(_translate("MainWindow", "Max"))
        self.lbCursorPos.setText(_translate("MainWindow", "Calibration markers id and position:"))
        self.btnCamParLoad.setText(_translate("MainWindow", "Load Ueye Camera Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Ueye"))
        self.label_11.setText(_translate("MainWindow", "Domain: x"))
        self.label_12.setText(_translate("MainWindow", "Domain: y"))
        self.lbDomX.setText(_translate("MainWindow", "Domain: x"))
        self.lbDomY.setText(_translate("MainWindow", "Domain: x"))
        self.btnMeas.setText(_translate("MainWindow", "Start Measurement"))
        self.label_7.setText(_translate("MainWindow", "Output gain:"))
        self.btnVizView.setText(_translate("MainWindow", "Rotate Visualization"))
        self.chkVizInvert.setText(_translate("MainWindow", "Invert"))
        self.chkStoreVids.setText(_translate("MainWindow", "Store video"))
        self.lbControl_2.setText(_translate("MainWindow", "Observer:"))
        self.rbObsVis.setText(_translate("MainWindow", "Vision"))
        self.rbObsVisUKF.setText(_translate("MainWindow", "VisionUKF"))
        self.rbObsOdomUKF.setText(_translate("MainWindow", "rbObsOdo"))
        self.rbObsFuse.setText(_translate("MainWindow", "rbObsFuse"))
        self.rbObsNone.setText(_translate("MainWindow", "rvObsNone"))
        self.lbControl_3.setText(_translate("MainWindow", "Intermediate Controller"))
        self.rbInterNone.setText(_translate("MainWindow", "None"))
        self.rbInterDWA.setText(_translate("MainWindow", "DWA"))
        self.rbInterPredict.setText(_translate("MainWindow", "Predictor"))
        self.lbControl.setText(_translate("MainWindow", "Control"))
        self.rbControlCenter.setText(_translate("MainWindow", "Center"))
        self.rbControlCustom.setText(_translate("MainWindow", "Custom"))
        self.rbControlMouse.setText(_translate("MainWindow", "Mouse"))
        self.rbControlRotation.setText(_translate("MainWindow", "Rotational field"))
        self.rbControlCoverage.setText(_translate("MainWindow", "Coverage"))
        self.rbControlGamePad.setText(_translate("MainWindow", "GamePad"))
        self.rbControlConstant.setText(_translate("MainWindow", "Constant"))
        self.rbControlNone.setText(_translate("MainWindow", "None"))
        self.labelOverlay_2.setText(_translate("MainWindow", "Output"))
        self.rbOutputElisa3.setText(_translate("MainWindow", "Elisa3"))
        self.rbOutputNone.setText(_translate("MainWindow", "None"))
        self.rbOutputSim.setText(_translate("MainWindow", "Simulator"))
        self.rbOutputOpen.setText(_translate("MainWindow", "Open"))
        self.btnReloadCfg.setText(_translate("MainWindow", "Reload configs"))
        self.btnPathRecalc.setText(_translate("MainWindow", "Recalculate paths"))
        self.chkRetrieveOdometry.setText(_translate("MainWindow", "Retrieve Odometry"))
        self.lbElisaGain.setText(_translate("MainWindow", "Gain: 1"))
        self.lbControl_4.setText(_translate("MainWindow", "Runoff"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
